-- =====================================================================
-- Migração: inventário via planilha (item #13)
-- =====================================================================
-- Idempotente. Cria uma tabela para registrar cada "lote" de contagem de
-- estoque feita via importação de planilha (data, usuário, quantos
-- produtos foram ajustados), e liga cada movimentação de estoque gerada
-- por essa contagem a esse lote — assim dá pra distinguir um ajuste de
-- inventário em massa de um ajuste manual avulso (que continua sem
-- inventario_id, como sempre foi).

create table if not exists public.inventarios (
    id bigint generated by default as identity primary key,
    usuario text,
    total_produtos integer not null default 0,
    total_ajustados integer not null default 0,
    observacao text,
    created_at timestamptz not null default now()
);

alter table public.estoque_movimentacoes add column if not exists inventario_id bigint references public.inventarios(id) on delete set null;
create index if not exists idx_estoque_mov_inventario on public.estoque_movimentacoes(inventario_id);
