-- =====================================================================
-- MIGRAÇÃO: 17 funcionalidades — Financeiro (F1-F8) e Produtos (P1-P9)
-- =====================================================================
-- Rode este script no SQL Editor do seu projeto Supabase.
-- Todo o script é idempotente (create table if not exists / add column
-- if not exists) — pode ser executado quantas vezes for preciso sem
-- apagar dados existentes.
--
-- IMPORTANTE: assume-se que produtos.id, despesas.id e historico_vendas.id
-- são do tipo bigint (padrão observado no restante do schema, diferente
-- das tabelas mais novas como eventos/ingressos que usam uuid). Se a sua
-- tabela "clientes" já existir com id uuid, ajuste os tipos
-- "bigint references" abaixo antes de rodar.
-- =====================================================================

-- ---------------------------------------------------------------------
-- F7. FORNECEDORES (base compartilhada por Despesas e Produtos)
-- ---------------------------------------------------------------------
create table if not exists public.fornecedores (
    id bigint generated by default as identity primary key,
    nome text not null,
    categoria text default 'OUTROS', -- livre, sugestao: BEBIDAS, CARNES, HORTIFRUTI, DESCARTAVEIS, SERVICOS, OUTROS
    telefone text,
    cnpj_cpf text,
    email text,
    endereco text,
    observacoes text,
    ativo boolean not null default true,
    created_at timestamptz not null default now()
);
create index if not exists idx_fornecedores_ativo on public.fornecedores(ativo);

-- Liga despesas a um fornecedor (opcional — a descricao livre continua
-- funcionando exatamente como hoje quando fornecedor_id for null)
alter table public.despesas add column if not exists fornecedor_id bigint references public.fornecedores(id) on delete set null;

-- ---------------------------------------------------------------------
-- P1, P2, P3, P4, P9. CAMPOS NOVOS EM PRODUTOS
-- ---------------------------------------------------------------------
-- preco_custo e estoque_minimo ja sao LIDOS em partes do sistema hoje
-- (dashboard.js e print-relatorios.js) — este ADD COLUMN IF NOT EXISTS
-- e seguro mesmo que a coluna ja exista.
alter table public.produtos add column if not exists preco_custo numeric(10,2) default 0;
alter table public.produtos add column if not exists estoque_minimo numeric(10,2) default 0;
alter table public.produtos add column if not exists fornecedor_id bigint references public.fornecedores(id) on delete set null;
alter table public.produtos add column if not exists codigo_barras text;
alter table public.produtos add column if not exists foto text;      -- URL do Supabase Storage
alter table public.produtos add column if not exists galeria jsonb;  -- array de fotos extras (ja lido em cardapio.js)

-- SKU/codigo de barras unico, mas permite multiplos produtos sem codigo
create unique index if not exists idx_produtos_codigo_barras
    on public.produtos(codigo_barras) where codigo_barras is not null;

-- ---------------------------------------------------------------------
-- P5. COMBOS COM COMPOSIÇÃO
-- ---------------------------------------------------------------------
create table if not exists public.produto_composicao (
    id bigint generated by default as identity primary key,
    combo_id bigint not null references public.produtos(id) on delete cascade,
    componente_id bigint not null references public.produtos(id) on delete restrict,
    quantidade numeric(10,3) not null default 1 check (quantidade > 0),
    created_at timestamptz not null default now(),
    check (combo_id <> componente_id),
    unique(combo_id, componente_id)
);
create index if not exists idx_composicao_combo on public.produto_composicao(combo_id);

-- ---------------------------------------------------------------------
-- P7. HISTÓRICO DE ALTERAÇÃO DE PREÇO
-- ---------------------------------------------------------------------
create table if not exists public.historico_precos (
    id bigint generated by default as identity primary key,
    produto_id bigint not null references public.produtos(id) on delete cascade,
    preco_antigo numeric(10,2),
    preco_novo numeric(10,2),
    usuario text,
    created_at timestamptz not null default now()
);
create index if not exists idx_historico_precos_produto on public.historico_precos(produto_id);

-- ---------------------------------------------------------------------
-- F1. CONTAS A RECEBER / FIADO
-- ---------------------------------------------------------------------
-- Garante que "clientes" existe com os campos minimos que o F1 precisa,
-- sem alterar o que ja existe hoje (limite_fiado ja e lido em dashboard.js).
create table if not exists public.clientes (
    id bigint generated by default as identity primary key,
    nome text,
    telefone text,
    limite_fiado numeric(10,2) default 0,
    created_at timestamptz not null default now()
);
alter table public.clientes add column if not exists nome text;
alter table public.clientes add column if not exists telefone text;
alter table public.clientes add column if not exists limite_fiado numeric(10,2) default 0;
create unique index if not exists idx_clientes_telefone on public.clientes(telefone) where telefone is not null;

create table if not exists public.contas_receber (
    id bigint generated by default as identity primary key,
    cliente_id bigint references public.clientes(id) on delete set null,
    venda_id bigint references public.historico_vendas(id) on delete set null,
    descricao text,
    valor numeric(10,2) not null check (valor >= 0),
    valor_pago numeric(10,2) not null default 0,
    vencimento date,
    status text not null default 'aberto' check (status in ('aberto','parcial','pago','cancelado')),
    data_pagamento timestamptz,
    forma_pagamento_baixa text,
    cadastrado_por text,
    created_at timestamptz not null default now()
);
create index if not exists idx_contas_receber_cliente on public.contas_receber(cliente_id);
create index if not exists idx_contas_receber_status on public.contas_receber(status);

-- ---------------------------------------------------------------------
-- F4. METAS DE FATURAMENTO
-- ---------------------------------------------------------------------
create table if not exists public.metas_faturamento (
    id bigint generated by default as identity primary key,
    ano integer not null,
    mes integer not null check (mes between 1 and 12),
    valor_meta numeric(10,2) not null default 0,
    observacao text,
    created_at timestamptz not null default now(),
    unique(ano, mes)
);

-- =====================================================================
-- F2, F3, F5, F6, P6, P8: não exigem novas tabelas/colunas.
-- F2 (DRE) usa produtos.preco_custo (acima). F3 (fluxo projetado) usa
-- despesas + contas_receber (acima). F5, F6, P6 são apenas novas
-- agregações sobre tabelas já existentes. P8 escreve diretamente em
-- produtos via upsert, sem tabela auxiliar.
-- =====================================================================

-- =====================================================================
-- OPCIONAL, MAS RECOMENDADO: Row Level Security (RLS)
-- =====================================================================
-- Mesma observação da migração de ingressos: como o client roda com a
-- chave pública (anon key), sem RLS qualquer pessoa com o endpoint pode
-- ler/escrever estas tabelas diretamente pela API. Ajuste à sua
-- estratégia de autenticação real antes de ir para produção.
--
-- alter table public.fornecedores enable row level security;
-- alter table public.produto_composicao enable row level security;
-- alter table public.historico_precos enable row level security;
-- alter table public.clientes enable row level security;
-- alter table public.contas_receber enable row level security;
-- alter table public.metas_faturamento enable row level security;
--
-- create policy "Leitura publica" on public.fornecedores for select using (true);
-- create policy "Escrita publica" on public.fornecedores for insert with check (true);
-- create policy "Atualizacao publica" on public.fornecedores for update using (true);
-- -- (repita o padrão acima para produto_composicao, historico_precos,
-- --  clientes, contas_receber e metas_faturamento conforme necessário)
