-- =====================================================================
-- ESPETINHO & CIA — SCHEMA COMPLETO PARA UM BANCO NOVO (DO ZERO)
-- =====================================================================
-- Este arquivo cria TODAS as tabelas do sistema inteiro (não apenas as
-- 17 funcionalidades novas de Financeiro/Produtos) como elas existem
-- hoje em produção, prontas para um projeto Supabase novo e vazio —
-- "como se fosse um sistema começando agora".
--
-- Ao final, o arquivo também insere o catálogo de produtos atual (41
-- itens, exportados do banco em produção em 2026-07-29), para não ser
-- necessário recadastrar tudo manualmente num sistema novo.
--
-- COMO USAR:
--   1. Crie um novo projeto no Supabase.
--   2. Copie a URL e a chave anon do novo projeto para componentes/config.js.
--   3. Rode este arquivo inteiro no SQL Editor do novo projeto (uma vez só).
--      IMPORTANTE: projetos novos do Supabase vêm com Row Level Security
--      (RLS) ligado por padrão em toda tabela nova, SEM nenhuma política —
--      isso bloqueia silenciosamente a leitura (a tela fica vazia, sem
--      erro) e bloqueia a escrita com o erro "new row violates row-level
--      security policy". Este script já inclui, logo abaixo, o comando
--      que desliga o RLS em todas as tabelas para igualar ao
--      comportamento do sistema em produção hoje (que não usa RLS) — não
--      é um passo separado, já roda junto quando você executa o arquivo
--      inteiro.
--   4. Rode os dois arquivos abaixo, NESTA ORDEM, por cima deste (eles são
--      idempotentes e cobrem as ALTER TABLE mais recentes com comentários
--      explicando o histórico de cada mudança — redundante com o que já
--      foi criado abaixo, mas seguro de rodar):
--        - arq/migracao-funcionalidades-2026.sql
--        - arq/migracao-ingressos.sql
--      (Se você rodar SOMENTE este arquivo schema-completo, já terá tudo
--      que os dois arquivos acima criam — eles só existem separados por
--      registrarem o histórico incremental de como o sistema evoluiu.)
--   5. Crie um usuário administrador (veja o INSERT comentado no final
--      da seção USUARIOS abaixo) com uma senha à sua escolha.
--   6. Os buckets de Storage ("produtos" e "eventos") e as permissões
--      deles já são criados por este script (seção 6.2) — não precisa
--      criar pelo Dashboard. O Storage do Supabase tem seu PRÓPRIO
--      sistema de RLS (storage.objects), separado do RLS das tabelas
--      normais desligado na seção 6.1 — por isso os dois precisam de
--      tratamento explícito, um não desliga o outro.
--
-- SEGURANÇA — LEIA ANTES DE COLOCAR EM PRODUÇÃO:
--   O client desta aplicação roda inteiramente no navegador com a chave
--   pública (anon key) do Supabase, sem backend próprio. Este script
--   desliga o RLS (Row Level Security) em todas as tabelas (seção 6.1)
--   para o app funcionar exatamente como a produção atual — o que
--   também significa que qualquer pessoa que descobrir a URL/chave do
--   seu projeto pode ler e escrever diretamente nestas tabelas pela API
--   REST do Supabase, inclusive a tabela "usuarios" (que hoje guarda
--   senhas em TEXTO PURO, sem hash — ver arq/auditoria-tecnica-2026-07-27.md
--   para o levantamento completo desse ponto). A correção definitiva
--   (hash de senha + autenticação real via Supabase
--   Auth) está fora do escopo deste script e deve ser tratada à parte.
--
-- Todo o script é idempotente (create table if not exists / add column
-- if not exists) — pode ser executado mais de uma vez sem apagar dados.
-- =====================================================================

create extension if not exists "pgcrypto";

-- =====================================================================
-- 1. USUÁRIOS E AUDITORIA
-- =====================================================================

create table if not exists public.usuarios (
    id bigint generated by default as identity primary key,
    usuario text not null,
    senha text not null, -- ATENÇÃO: texto puro hoje, sem hash (ver aviso de segurança acima)
    nome text,
    role text default 'operador',
    nivel text default 'GARCOM', -- ADMIN, OPERADOR, GARCOM (usado para permissões na UI)
    ativo boolean not null default true,
    recebe_notificacoes boolean not null default false,
    modo_impressao text, -- preferência local de impressão do usuário (rawbt, pc, etc.)
    created_at timestamptz not null default now()
);
create unique index if not exists idx_usuarios_usuario on public.usuarios(usuario);

create table if not exists public.auditoria (
    id bigint generated by default as identity primary key,
    usuario text,
    tipo text, -- VENDA, ESTOQUE, FINANCEIRO, SEGURANÇA, SISTEMA...
    action text,
    description text,
    created_at timestamptz not null default now()
);
create index if not exists idx_auditoria_created_at on public.auditoria(created_at desc);

-- =====================================================================
-- 2. FORNECEDORES E CLIENTES (bases compartilhadas)
-- =====================================================================

create table if not exists public.fornecedores (
    id bigint generated by default as identity primary key,
    nome text not null,
    categoria text default 'OUTROS', -- livre, sugestão: BEBIDAS, CARNES, HORTIFRUTI, DESCARTAVEIS, SERVICOS, OUTROS
    telefone text,
    cnpj_cpf text,
    email text,
    endereco text,
    observacoes text,
    ativo boolean not null default true,
    created_at timestamptz not null default now()
);
create index if not exists idx_fornecedores_ativo on public.fornecedores(ativo);

create table if not exists public.clientes (
    id bigint generated by default as identity primary key,
    nome text,
    telefone text,
    limite_fiado numeric(10,2) default 0,
    created_at timestamptz not null default now()
);
create unique index if not exists idx_clientes_telefone on public.clientes(telefone) where telefone is not null;

-- =====================================================================
-- 3. PRODUTOS, ESTOQUE E COMBOS
-- =====================================================================

create table if not exists public.produtos (
    id bigint generated by default as identity primary key,
    nome text not null,
    preco numeric(10,2) not null default 0,
    categoria text not null, -- espetos, bebidas, cervejas, refeicao, acompanhamentos, combos
    status boolean not null default true, -- ativo/inativo no catálogo
    estoque integer default 0, -- legado, não utilizado pelo app atual (usar estoque_atual)
    estoque_atual numeric(10,2) default 0,
    controlar_estoque boolean not null default false,
    estoque_minimo numeric(10,2) default 0,
    precisa_preparo boolean not null default true, -- aparece na tela da churrasqueira/cozinha
    pedir_complementos boolean not null default true,
    ingredientes text,
    observacao text,
    preco_custo numeric(10,2) default 0,
    fornecedor_id bigint references public.fornecedores(id) on delete set null,
    codigo_barras text,
    foto text,      -- URL no Supabase Storage (bucket "produtos")
    galeria jsonb,   -- array de fotos extras, opcional
    created_at timestamptz not null default now()
);
create unique index if not exists idx_produtos_codigo_barras
    on public.produtos(codigo_barras) where codigo_barras is not null;
create index if not exists idx_produtos_categoria on public.produtos(categoria);

create table if not exists public.produto_composicao (
    id bigint generated by default as identity primary key,
    combo_id bigint not null references public.produtos(id) on delete cascade,
    componente_id bigint not null references public.produtos(id) on delete restrict,
    quantidade numeric(10,3) not null default 1 check (quantidade > 0),
    created_at timestamptz not null default now(),
    check (combo_id <> componente_id),
    unique(combo_id, componente_id)
);
create index if not exists idx_composicao_combo on public.produto_composicao(combo_id);

create table if not exists public.historico_precos (
    id bigint generated by default as identity primary key,
    produto_id bigint not null references public.produtos(id) on delete cascade,
    preco_antigo numeric(10,2),
    preco_novo numeric(10,2),
    usuario text,
    created_at timestamptz not null default now()
);
create index if not exists idx_historico_precos_produto on public.historico_precos(produto_id);

create table if not exists public.inventarios (
    id bigint generated by default as identity primary key,
    usuario text,
    total_produtos integer not null default 0,
    total_ajustados integer not null default 0,
    observacao text,
    created_at timestamptz not null default now()
);

create table if not exists public.estoque_movimentacoes (
    id bigint generated by default as identity primary key,
    produto_id bigint references public.produtos(id) on delete cascade,
    tipo text not null, -- entrada, saida
    quantidade numeric(10,2) not null default 0,
    motivo text,
    usuario text,
    inventario_id bigint references public.inventarios(id) on delete set null,
    created_at timestamptz not null default now()
);
create index if not exists idx_estoque_mov_produto on public.estoque_movimentacoes(produto_id);
create index if not exists idx_estoque_mov_inventario on public.estoque_movimentacoes(inventario_id);

create table if not exists public.complementos (
    id uuid primary key default gen_random_uuid(),
    nome text not null,
    tipo text, -- categoria do complemento (ex: farinha, molho, ...)
    ativo boolean not null default true,
    criado_em timestamptz not null default now()
);

-- =====================================================================
-- 4. CAIXA, COMANDAS E VENDAS
-- =====================================================================

create table if not exists public.caixa (
    id bigint generated by default as identity primary key,
    aberto_em timestamptz not null default now(),
    fechado_em timestamptz,
    valor_inicial numeric(10,2) default 0,
    valor_final_dinheiro numeric(10,2),
    valor_final_cartao numeric(10,2),
    valor_final_pix numeric(10,2),
    status text not null default 'aberto', -- aberto, fechado
    criado_por text
);

create table if not exists public.movimentacoes_caixa (
    id bigint generated by default as identity primary key,
    id_caixa bigint references public.caixa(id) on delete cascade,
    tipo text not null, -- SUPRIMENTO, SANGRIA
    valor numeric(10,2) not null default 0,
    motivo text,
    usuario text,
    created_at timestamptz not null default now()
);
create index if not exists idx_mov_caixa_id_caixa on public.movimentacoes_caixa(id_caixa);

create table if not exists public.comandas (
    id bigint generated by default as identity primary key,
    identificacao text not null, -- número/nome da mesa
    itens jsonb not null default '[]'::jsonb,
    total numeric(10,2) not null default 0,
    status text not null default 'aberta', -- aberta, fechada, cancelada
    vendedor text,
    aberta_em timestamptz not null default now(),
    fechada_em timestamptz,
    estornado_em timestamptz,
    autorizado_por text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index if not exists idx_comandas_status on public.comandas(status);

create table if not exists public.historico_vendas (
    id bigint generated by default as identity primary key,
    itens jsonb not null default '[]'::jsonb,
    total numeric(10,2) not null default 0,
    desconto numeric(10,2) default 0,
    taxa_servico numeric(10,2) default 0,
    forma_pagamento text,
    valor_recebido numeric(10,2),
    troco numeric(10,2) default 0,
    status text not null default 'concluida', -- concluida, cancelada, estornada
    vendedor text,
    atendente text,
    comanda_id bigint references public.comandas(id) on delete set null,
    comanda_origem text,
    cliente_id bigint references public.clientes(id) on delete set null,
    id_caixa bigint references public.caixa(id) on delete set null,
    autorizado_por text,
    estornado_em timestamptz,
    criado_em timestamptz not null default now(),
    created_at timestamptz not null default now()
);
create index if not exists idx_historico_vendas_created_at on public.historico_vendas(created_at desc);
create index if not exists idx_historico_vendas_status on public.historico_vendas(status);

-- =====================================================================
-- 5. FINANCEIRO (DESPESAS, CONTAS A RECEBER, METAS)
-- =====================================================================

create table if not exists public.despesas (
    id bigint generated by default as identity primary key,
    descricao text not null,
    valor numeric(10,2) not null default 0,
    categoria text,
    vencimento date,
    paga boolean not null default false,
    data_pagamento date,
    cadastrado_por text,
    fornecedor_id bigint references public.fornecedores(id) on delete set null,
    created_at timestamptz not null default now()
);
create index if not exists idx_despesas_vencimento on public.despesas(vencimento);
create index if not exists idx_despesas_paga on public.despesas(paga);

create table if not exists public.contas_receber (
    id bigint generated by default as identity primary key,
    cliente_id bigint references public.clientes(id) on delete set null,
    venda_id bigint references public.historico_vendas(id) on delete set null,
    descricao text,
    valor numeric(10,2) not null check (valor >= 0),
    valor_pago numeric(10,2) not null default 0,
    vencimento date,
    status text not null default 'aberto' check (status in ('aberto','parcial','pago','cancelado')),
    data_pagamento timestamptz,
    forma_pagamento_baixa text,
    cadastrado_por text,
    created_at timestamptz not null default now()
);
create index if not exists idx_contas_receber_cliente on public.contas_receber(cliente_id);
create index if not exists idx_contas_receber_status on public.contas_receber(status);

create table if not exists public.metas_faturamento (
    id bigint generated by default as identity primary key,
    ano integer not null,
    mes integer not null check (mes between 1 and 12),
    valor_meta numeric(10,2) not null default 0,
    observacao text,
    created_at timestamptz not null default now(),
    unique(ano, mes)
);

create table if not exists public.configuracoes_sistema (
    id bigint generated by default as identity primary key,
    chave text,   -- padrão chave/valor legado (ex: 'ticket_layout')
    valor text,
    nome_loja text,
    cnpj text,
    ticket_layout text,
    telefone text,
    endereco text,
    ordem_categorias text,
    updated_at timestamptz not null default now()
);

-- =====================================================================
-- 6. EVENTOS E INGRESSOS
-- =====================================================================

create table if not exists public.eventos (
    id uuid primary key default gen_random_uuid(),
    nome text not null,
    data_evento timestamptz,
    valor_mesa numeric(10,2) default 0,
    quantidade_mesas integer default 0,
    mapa_url text, -- URL (Supabase Storage) ou, em registros antigos, imagem em base64 inline
    status text default 'ativo', -- ativo, finalizado, cancelado
    whatsapp_notificacao text,
    patrocinadores jsonb, -- array de {nome}
    created_at timestamptz not null default now()
);

create table if not exists public.reservas_evento (
    id uuid primary key default gen_random_uuid(),
    evento_id uuid not null references public.eventos(id) on delete cascade,
    mesas jsonb, -- array de números de mesa reservados, ex: [12, 13]
    cliente_nome text,
    cliente_telefone text,
    comprovante_url text,
    status text default 'pendente', -- pendente, confirmada, cancelada
    created_at timestamptz not null default now()
);
create index if not exists idx_reservas_evento_evento on public.reservas_evento(evento_id);

create table if not exists public.tipos_ingresso (
    id uuid primary key default gen_random_uuid(),
    evento_id uuid not null references public.eventos(id) on delete cascade,
    nome text not null,
    preco numeric(10,2) not null check (preco >= 0),
    quantidade_total integer, -- null = sem limite de quantidade
    quantidade_vendida integer not null default 0,
    ativo boolean not null default true,
    created_at timestamptz not null default now()
);
create index if not exists idx_tipos_ingresso_evento on public.tipos_ingresso(evento_id);

create table if not exists public.ingressos (
    id uuid primary key default gen_random_uuid(),
    evento_id uuid not null references public.eventos(id) on delete cascade,
    tipo_ingresso_id uuid not null references public.tipos_ingresso(id) on delete restrict,
    codigo_unico uuid not null default gen_random_uuid() unique,
    comprador_nome text not null,
    comprador_telefone text,
    canal_venda text not null check (canal_venda in ('balcao', 'publico')),
    valor_pago numeric(10,2) not null default 0,
    status text not null default 'pendente' check (status in ('pendente', 'confirmado', 'utilizado', 'cancelado')),
    vendido_por text,
    data_venda timestamptz not null default now(),
    data_utilizacao timestamptz,
    validado_por text,
    created_at timestamptz not null default now()
);
create index if not exists idx_ingressos_evento on public.ingressos(evento_id);
create index if not exists idx_ingressos_codigo on public.ingressos(codigo_unico);
create index if not exists idx_ingressos_status on public.ingressos(status);

-- =====================================================================
-- 6.1. DESLIGA RLS (projetos novos do Supabase vêm com RLS ligado por
-- padrão e sem nenhuma política, o que bloqueia silenciosamente leitura
-- e escrita para o client desta aplicação, que usa só a chave pública).
-- Isso iguala ao comportamento do sistema em produção hoje, que não usa
-- RLS. Ver aviso de segurança no topo deste arquivo.
-- =====================================================================
do $$
declare
  t text;
begin
  for t in
    select unnest(array[
      'usuarios','auditoria','fornecedores','clientes','produtos',
      'produto_composicao','historico_precos','estoque_movimentacoes',
      'complementos','caixa','movimentacoes_caixa','comandas',
      'historico_vendas','despesas','contas_receber','metas_faturamento',
      'configuracoes_sistema','eventos','reservas_evento',
      'tipos_ingresso','ingressos'
    ])
  loop
    execute format('alter table public.%I disable row level security;', t);
  end loop;
end $$;

-- =====================================================================
-- 6.2. BUCKETS DE STORAGE ("produtos" e "eventos") + PERMISSÕES
-- =====================================================================
-- O código só usa getPublicUrl() (nunca link assinado), então os
-- buckets precisam ser públicos para a foto aparecer em qualquer tela.
-- storage.objects tem RLS sempre ligado no Supabase (não dá pra
-- desligar como nas tabelas normais) — por isso aqui é preciso criar
-- políticas explícitas de leitura/escrita para a chave pública (anon),
-- separado do bloco 6.1 acima.
--
-- Limites aplicados: 5MB por arquivo, apenas imagens (jpeg/png/webp/
-- heic/heif — heic/heif cobre fotos direto de iPhone). Ajuste
-- file_size_limit (em bytes) se quiser outro limite.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
    ('produtos', 'produtos', true, 5242880, array['image/jpeg','image/png','image/webp','image/heic','image/heif']),
    ('eventos', 'eventos', true, 5242880, array['image/jpeg','image/png','image/webp','image/heic','image/heif'])
on conflict (id) do nothing;

do $$
declare
  b text;
  acao text;
begin
  for b in select unnest(array['produtos', 'eventos'])
  loop
    foreach acao in array array['Leitura', 'Escrita', 'Atualizacao', 'Exclusao']
    loop
      execute format('drop policy if exists "%s publica bucket %s" on storage.objects;', acao, b);
    end loop;
    execute format('create policy "Leitura publica bucket %s" on storage.objects for select using (bucket_id = %L);', b, b);
    execute format('create policy "Escrita publica bucket %s" on storage.objects for insert with check (bucket_id = %L);', b, b);
    execute format('create policy "Atualizacao publica bucket %s" on storage.objects for update using (bucket_id = %L);', b, b);
    execute format('create policy "Exclusao publica bucket %s" on storage.objects for delete using (bucket_id = %L);', b, b);
  end loop;
end $$;

-- =====================================================================
-- 7. USUÁRIO ADMINISTRADOR INICIAL
-- =====================================================================
-- Descomente e ajuste a linha abaixo para criar o primeiro login do
-- sistema novo. Troque 'TROQUE_ESTA_SENHA' por uma senha sua — lembre
-- que, hoje, o sistema NÃO faz hash de senha (ver aviso de segurança).
--
-- insert into public.usuarios (usuario, senha, nome, role, nivel, ativo)
-- values ('admin', 'TROQUE_ESTA_SENHA', 'ADMINISTRADOR', 'admin', 'ADMIN', true);

-- =====================================================================
-- 8. SEED: CATÁLOGO DE PRODUTOS ATUAL
-- =====================================================================
-- Exportado do banco em produção em 2026-07-29 (41 produtos). Os IDs
-- originais são preservados para manter compatibilidade caso você
-- também importe dados históricos depois; a sequência é realinhada ao
-- final para que novos produtos cadastrados pela UI continuem a partir
-- do próximo ID livre.

insert into public.produtos
    (id, nome, preco, categoria, status, estoque, estoque_atual, controlar_estoque, estoque_minimo, precisa_preparo, pedir_complementos, ingredientes, observacao, preco_custo, created_at)
overriding system value
values
    (1, 'ESPETINHO DE BOI', 10, 'espetos', false, 0, 0, false, 0, false, true, '', null, null, '2025-12-24T18:11:50.49821+00:00'),
    (2, 'ESPETINHO DE FRANGO', 10, 'espetos', false, 0, 0, false, 0, false, false, '', null, null, '2025-12-24T18:11:50.49821+00:00'),
    (3, 'JANTINHA', 25, 'refeicao', true, 0, -24, false, 0, false, false, 'Arroz ir, vinagreti, farofa, feijão tropeiro', null, null, '2025-12-24T18:11:50.49821+00:00'),
    (4, 'PÃO DE ALHO', 6, 'acompanhamentos', false, 0, 0, false, 0, true, true, null, null, null, '2025-12-24T18:11:50.49821+00:00'),
    (5, 'ESPETINHO DE QUEIJO COALHO', 10, 'espetos', false, 0, 0, false, 0, false, false, '', null, null, '2025-12-24T18:11:50.49821+00:00'),
    (6, 'BRAHMA LATÃO', 8, 'cervejas', false, 0, -5, false, 0, false, true, null, null, null, '2025-12-24T18:11:50.49821+00:00'),
    (7, 'REFRIGERANTE LATA', 6, 'bebidas', true, 0, 0, false, 0, false, false, '', 'Coca-cola, coca-cola zero, guaraná, guaraná zero', null, '2025-12-24T18:11:50.49821+00:00'),
    (8, 'ÁGUA MINERAL', 3, 'bebidas', true, 0, 0, false, 0, false, false, '', null, null, '2025-12-24T18:11:50.49821+00:00'),
    (9, 'SUCO NATURAL', 6, 'bebidas', false, 0, -4, false, 0, false, true, null, null, null, '2025-12-24T18:11:50.49821+00:00'),
    (10, 'AMSTEL LATÃO', 8, 'cervejas', false, 0, -2, false, 0, false, true, null, null, null, '2025-12-27T18:53:22.417368+00:00'),
    (11, 'ÁGUA MINERAL COM GÁS', 5, 'bebidas', true, 0, 0, false, 0, false, true, null, null, null, '2026-03-03T20:16:52.950357+00:00'),
    (12, 'HEINEKEN LONGNECK', 11, 'cervejas', true, 0, 6, false, 0, false, false, '', null, null, '2026-03-03T20:18:41.267445+00:00'),
    (13, 'STELLA GOLD LONGNECK', 12, 'cervejas', true, 0, -1, false, 0, false, true, null, null, null, '2026-03-03T20:19:07.334495+00:00'),
    (14, 'ARROZ E FAROFA ', 20, 'refeicao', false, 0, -3, true, 0, true, true, null, null, null, '2026-03-07T16:39:36.860206+00:00'),
    (15, 'PRODUTO TESTE', 20, 'refeicao', false, 0, 12, true, 0, true, true, null, null, null, '2026-03-30T23:59:01.347778+00:00'),
    (16, 'ESPETINHO DE PORCO', 10, 'espetos', false, 0, 0, false, 0, false, false, '', null, null, '2026-05-06T00:15:22.38965+00:00'),
    (17, 'ESPETINHO DE CORAÇÃO', 10, 'espetos', false, 0, 0, false, 0, false, false, '', null, null, '2026-05-06T00:15:53.971934+00:00'),
    (18, 'MEDALHÃO', 15, 'espetos', false, 0, 0, false, 0, false, false, '', '', null, '2026-05-06T00:16:20.433398+00:00'),
    (19, 'ESPETINHO DE LINGUICINHA', 9, 'espetos', false, 0, 0, false, 0, false, false, '', null, null, '2026-05-06T00:17:05.965895+00:00'),
    (20, 'LINGUIÇA COFRIL', 9, 'espetos', false, 0, 0, false, 0, false, false, '', null, null, '2026-05-06T00:17:33.744545+00:00'),
    (21, 'HEINEKEN 600ML', 16, 'cervejas', false, 0, 0, false, 0, false, true, null, null, null, '2026-05-06T00:44:12.952424+00:00'),
    (22, 'AMSTEL 600ML', 13, 'cervejas', false, 0, 0, false, 0, false, true, null, null, null, '2026-05-06T00:44:40.804766+00:00'),
    (23, 'CORONA LONGNECK', 12, 'cervejas', true, 0, 0, false, 0, false, true, null, null, null, '2026-05-06T00:46:06.597107+00:00'),
    (24, 'REDBULL', 15, 'bebidas', true, 0, 0, false, 0, false, false, '', 'tradicional', null, '2026-05-11T11:18:03.50942+00:00'),
    (25, 'SKOL BEATS', 12, 'bebidas', true, 0, 0, false, 0, false, false, '', 'GT, red mix', null, '2026-05-11T11:18:26.218643+00:00'),
    (26, 'PINKMOON FRISANTE', 12, 'bebidas', true, 0, 0, false, 0, false, false, '', 'Rosé, Pêssego', null, '2026-05-11T11:19:00.951488+00:00'),
    (27, 'ESPETINHO', 10, 'espetos', true, 0, 0, false, 0, false, false, '', '', 0, '2026-05-11T11:20:45.684612+00:00'),
    (28, 'PORÇÃO DE FRITAS', 25, 'acompanhamentos', true, 0, 0, false, 0, false, false, '', null, null, '2026-05-11T11:21:32.605092+00:00'),
    (29, 'PORÇÃO MEIO DA ASA', 25, 'acompanhamentos', false, 0, 0, false, 0, false, true, null, null, null, '2026-05-11T11:22:09.169046+00:00'),
    (30, 'WEMIX', 10, 'bebidas', true, 0, 0, false, 0, false, false, '', 'morango', null, '2026-05-14T11:05:32.803913+00:00'),
    (31, 'HEINEKEN COMBO (6 UND.)', 65, 'combos', true, 0, 0, false, 0, false, false, '', null, null, '2026-05-14T11:06:22.546464+00:00'),
    (32, 'CORONA COMBO (6 UND.)', 70, 'combos', true, 0, 0, false, 0, false, false, '', null, null, '2026-05-14T11:06:44.931286+00:00'),
    (33, 'STELLA GOLD COMBO (6 UND.)', 70, 'combos', true, 0, 0, false, 0, false, false, '', null, null, '2026-05-14T11:07:13.205651+00:00'),
    (34, 'CAMPARI - DOSE', 15, 'bebidas', true, 0, 0, false, 0, false, true, null, null, null, '2026-05-14T11:07:31.140777+00:00'),
    (35, 'PÃO COM LINGUIÇA E VINAGRETE', 18, 'acompanhamentos', false, 0, 0, false, 0, true, true, null, null, null, '2026-05-20T00:13:03.952715+00:00'),
    (36, 'AMSTEL LATÃO COMBO (6 UND.)', 48, 'combos', false, 0, 0, false, 0, false, false, '', null, null, '2026-06-11T23:39:24.079367+00:00'),
    (38, 'RESERVA MESA', 50, 'combos', false, 0, 0, false, 0, false, false, '', null, null, '2026-06-13T20:46:35.253086+00:00'),
    (39, 'BRAHMA LATA', 6, 'cervejas', false, 0, 0, false, 0, false, false, '', '', null, '2026-06-19T22:01:35.161922+00:00'),
    (40, 'CADEIRA AVULSA', 10, 'combos', false, 0, 0, false, 0, false, false, '', '', null, '2026-06-19T23:27:37.803315+00:00'),
    (41, 'CALDO DE FEIJÃO', 20, 'refeicao', false, 0, 0, false, 0, false, false, '', '', null, '2026-06-23T11:29:32.909609+00:00'),
    (42, 'BRAHMA LATÃO COMBO (6 UND.)', 48, 'combos', false, 0, 0, false, 0, false, false, '', '', null, '2026-06-24T16:12:05.453892+00:00')
on conflict (id) do nothing;

-- Realinha a sequência do id para continuar depois do maior ID inserido acima
select setval(pg_get_serial_sequence('public.produtos', 'id'), (select max(id) from public.produtos));

-- =====================================================================
-- SOBRE RLS NESTE PROJETO (já resolvido acima, seção 6.1)
-- =====================================================================
-- O bloco da seção 6.1 já desligou o RLS em todas as tabelas, igualando
-- ao comportamento do sistema em produção hoje. Isso é necessário porque
-- o client roda com a chave pública (anon key), sem backend próprio e
-- sem Supabase Auth — com RLS ligado e sem políticas, a tela fica vazia
-- e nenhuma escrita funciona.
--
-- Se um dia você migrar para autenticação real (Supabase Auth) e quiser
-- RLS de verdade (não apenas desligado), a alternativa é RE-ligar o RLS
-- por tabela e criar políticas específicas por papel de usuário — isso
-- é um trabalho de segurança à parte, fora do escopo deste script. Por
-- ora, manter RLS desligado é o que faz o sistema funcionar exatamente
-- como a produção atual.
