-- =====================================================================
-- WEBCOMANDA ESPETINHO V3
-- SCHEMA BASE — BANCO V3 INICIAL
-- =====================================================================
-- STATUS: RASCUNHO ARQUITETURAL / NÃO EXECUTAR AINDA
-- Este schema é uma fundação provisória e será revisado quando o modelo V3
-- estiver fechado. O banco físico final será criado de uma vez mais adiante.
--
-- Este arquivo é para um banco V3 NOVO.
--
-- Ele NÃO é uma migration da V2.
-- Ele cria a fundação relacional da V3 desde o início.
--
-- Ordem recomendada:
--   1. executar este schema em banco de desenvolvimento;
--   2. executar arq/seeds-v3/001-bootstrap-administrativo.sql;
--   3. validar a estrutura;
--   4. configurar URL/chave na aplicação;
--   5. executar os testes documentados.
--
-- IMPORTANTE:
--   * não cria senha em texto puro;
--   * não ativa RLS nesta primeira fundação, pois a sessão atual ainda
--     é herdada temporariamente da V2;
--   * RLS e autenticação própria da V3 entram em etapa posterior.
-- =====================================================================

begin;

create extension if not exists pgcrypto;

-- =====================================================================
-- 1. EMPRESA
-- =====================================================================

create table if not exists public.empresas (
    id uuid primary key default gen_random_uuid(),
    nome text not null,
    documento text,
    status text not null default 'ativa'
        check (status in ('ativa', 'inativa')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_empresas_status
    on public.empresas(status);

-- =====================================================================
-- 2. UNIDADES
-- =====================================================================

create table if not exists public.unidades (
    id uuid primary key default gen_random_uuid(),
    empresa_id uuid not null
        references public.empresas(id) on delete restrict,
    nome text not null,
    codigo text,
    status text not null default 'ativa'
        check (status in ('ativa', 'inativa')),
    telefone text,
    endereco text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (empresa_id, nome),
    unique (empresa_id, codigo)
);

create index if not exists idx_unidades_empresa_id
    on public.unidades(empresa_id);

create index if not exists idx_unidades_status
    on public.unidades(status);

-- =====================================================================
-- 3. USUÁRIOS / PERFIL DA APLICAÇÃO
-- =====================================================================
-- A autenticação real será conectada ao Supabase Auth em etapa posterior.
-- Por isso auth_user_id é nullable.
--
-- Não existe coluna de senha nesta tabela V3.

create table if not exists public.usuarios (
    id bigint generated by default as identity primary key,
    auth_user_id uuid unique,
    usuario text not null unique,
    nome text not null,
    ativo boolean not null default true,
    recebe_notificacoes boolean not null default false,
    modo_impressao text not null default 'direto'
        check (modo_impressao in ('direto', 'pdf', 'navegador')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_usuarios_ativo
    on public.usuarios(ativo);

create index if not exists idx_usuarios_auth_user_id
    on public.usuarios(auth_user_id);

-- Se o Supabase Auth estiver disponível, manter a relação preparada.
do $$
begin
    if to_regclass('auth.users') is not null
       and not exists (
           select 1
           from pg_constraint
           where conname = 'fk_usuarios_auth_user'
             and conrelid = 'public.usuarios'::regclass
       ) then
        alter table public.usuarios
            add constraint fk_usuarios_auth_user
            foreign key (auth_user_id)
            references auth.users(id)
            on delete set null;
    end if;
exception
    when undefined_table then
        null;
end;
$$;

-- =====================================================================
-- 4. PAPÉIS
-- =====================================================================

create table if not exists public.papeis (
    id uuid primary key default gen_random_uuid(),
    codigo text not null unique,
    nome text not null,
    descricao text,
    ativo boolean not null default true,
    created_at timestamptz not null default now()
);

-- =====================================================================
-- 5. PERMISSÕES
-- =====================================================================

create table if not exists public.permissoes (
    id uuid primary key default gen_random_uuid(),
    codigo text not null unique,
    nome text not null,
    descricao text,
    created_at timestamptz not null default now()
);

-- =====================================================================
-- 6. PAPEL x PERMISSÃO
-- =====================================================================

create table if not exists public.papel_permissoes (
    papel_id uuid not null
        references public.papeis(id) on delete cascade,
    permissao_id uuid not null
        references public.permissoes(id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (papel_id, permissao_id)
);

-- =====================================================================
-- 7. MEMBROS DA ORGANIZAÇÃO
-- =====================================================================
-- unidade_id NULL = escopo empresarial.
-- unidade_id preenchido = escopo daquela unidade.

create table if not exists public.membros_organizacao (
    id uuid primary key default gen_random_uuid(),
    usuario_id bigint not null
        references public.usuarios(id) on delete cascade,
    empresa_id uuid not null
        references public.empresas(id) on delete cascade,
    unidade_id uuid
        references public.unidades(id) on delete cascade,
    papel_id uuid not null
        references public.papeis(id) on delete restrict,
    ativo boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_membros_usuario_id
    on public.membros_organizacao(usuario_id);

create index if not exists idx_membros_empresa_id
    on public.membros_organizacao(empresa_id);

create index if not exists idx_membros_unidade_id
    on public.membros_organizacao(unidade_id);

create index if not exists idx_membros_papel_id
    on public.membros_organizacao(papel_id);

create or replace function public.validar_membro_empresa_unidade_v3()
returns trigger
language plpgsql
as $$
begin
    if new.unidade_id is not null and not exists (
        select 1
        from public.unidades u
        where u.id = new.unidade_id
          and u.empresa_id = new.empresa_id
    ) then
        raise exception 'A unidade não pertence à empresa informada.';
    end if;

    return new;
end;
$$;

drop trigger if exists trg_validar_membro_empresa_unidade_v3
    on public.membros_organizacao;

create trigger trg_validar_membro_empresa_unidade_v3
before insert or update on public.membros_organizacao
for each row execute function public.validar_membro_empresa_unidade_v3();

-- =====================================================================
-- 8. AUDITORIA
-- =====================================================================

create table if not exists public.auditoria (
    id bigint generated by default as identity primary key,
    usuario_id bigint references public.usuarios(id) on delete set null,
    empresa_id uuid references public.empresas(id) on delete set null,
    unidade_id uuid references public.unidades(id) on delete set null,
    tipo text not null,
    action text not null,
    description text,
    entidade text,
    entidade_id text,
    origem text,
    sucesso boolean not null default true,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_auditoria_usuario_id
    on public.auditoria(usuario_id);

create index if not exists idx_auditoria_empresa_id
    on public.auditoria(empresa_id);

create index if not exists idx_auditoria_unidade_id
    on public.auditoria(unidade_id);

create index if not exists idx_auditoria_created_at
    on public.auditoria(created_at desc);

-- =====================================================================
-- 9. CONFIGURAÇÕES
-- =====================================================================
-- A configuração é hierárquica por escopo.
--
-- Exemplos:
--   escopo = global   -> configuração geral da instalação
--   escopo = empresa  -> empresa_id preenchido
--   escopo = unidade  -> empresa_id + unidade_id
--   escopo = usuario  -> usuario_id
--
-- valor é JSONB para permitir boolean, número, texto ou objeto sem
-- criar uma tabela nova a cada preferência.

create table if not exists public.configuracoes_sistema (
    id uuid primary key default gen_random_uuid(),
    escopo text not null
        check (escopo in ('global', 'empresa', 'unidade', 'usuario')),
    empresa_id uuid references public.empresas(id) on delete cascade,
    unidade_id uuid references public.unidades(id) on delete cascade,
    usuario_id bigint references public.usuarios(id) on delete cascade,
    chave text not null,
    valor jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (
        (escopo = 'global' and empresa_id is null and unidade_id is null and usuario_id is null)
        or
        (escopo = 'empresa' and empresa_id is not null and unidade_id is null and usuario_id is null)
        or
        (escopo = 'unidade' and empresa_id is not null and unidade_id is not null and usuario_id is null)
        or
        (escopo = 'usuario' and empresa_id is null and unidade_id is null and usuario_id is not null)
    )
);

create unique index if not exists ux_config_global
    on public.configuracoes_sistema(chave)
    where escopo = 'global';

create unique index if not exists ux_config_empresa
    on public.configuracoes_sistema(empresa_id, chave)
    where escopo = 'empresa';

create unique index if not exists ux_config_unidade
    on public.configuracoes_sistema(unidade_id, chave)
    where escopo = 'unidade';

create unique index if not exists ux_config_usuario
    on public.configuracoes_sistema(usuario_id, chave)
    where escopo = 'usuario';

-- =====================================================================
-- 10. PRODUTOS
-- =====================================================================

create table if not exists public.produtos (
    id bigint generated by default as identity primary key,
    empresa_id uuid not null
        references public.empresas(id) on delete restrict,
    nome text not null,
    categoria text,
    descricao text,
    observacao text,
    preco numeric(12,2) not null default 0
        check (preco >= 0),
    custo numeric(12,2)
        check (custo is null or custo >= 0),
    sku text,
    imagem_url text,
    galeria_urls jsonb not null default '[]'::jsonb,
    controlar_estoque boolean not null default false,
    estoque_minimo numeric(12,3) not null default 0
        check (estoque_minimo >= 0),
    ativo boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_produtos_empresa_id
    on public.produtos(empresa_id);

create index if not exists idx_produtos_categoria
    on public.produtos(empresa_id, categoria);

create unique index if not exists ux_produtos_empresa_sku
    on public.produtos(empresa_id, sku)
    where sku is not null;

-- =====================================================================
-- 11. COMPOSIÇÃO DE PRODUTOS / COMBOS
-- =====================================================================

create table if not exists public.produto_composicao (
    combo_id bigint not null
        references public.produtos(id) on delete cascade,
    produto_id bigint not null
        references public.produtos(id) on delete restrict,
    quantidade numeric(12,3) not null
        check (quantidade > 0),
    created_at timestamptz not null default now(),
    primary key (combo_id, produto_id),
    check (combo_id <> produto_id)
);

create index if not exists idx_produto_composicao_produto_id
    on public.produto_composicao(produto_id);

-- =====================================================================
-- 12. ESTOQUE POR UNIDADE
-- =====================================================================

create table if not exists public.estoque_produto_unidade (
    id uuid primary key default gen_random_uuid(),
    produto_id bigint not null
        references public.produtos(id) on delete cascade,
    unidade_id uuid not null
        references public.unidades(id) on delete restrict,
    saldo numeric(12,3) not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (produto_id, unidade_id)
);

create index if not exists idx_estoque_produto_unidade_unidade
    on public.estoque_produto_unidade(unidade_id);

create index if not exists idx_estoque_produto_unidade_produto
    on public.estoque_produto_unidade(produto_id);

-- =====================================================================
-- 13. INVENTÁRIOS
-- =====================================================================

create table if not exists public.inventarios (
    id bigint generated by default as identity primary key,
    empresa_id uuid not null
        references public.empresas(id) on delete restrict,
    unidade_id uuid not null
        references public.unidades(id) on delete restrict,
    usuario_id bigint
        references public.usuarios(id) on delete set null,
    operacao_id uuid unique,
    total_produtos integer not null default 0
        check (total_produtos >= 0),
    total_ajustados integer not null default 0
        check (total_ajustados >= 0),
    observacao text,
    status text not null default 'concluido'
        check (status in ('rascunho', 'concluido', 'cancelado')),
    created_at timestamptz not null default now()
);

create index if not exists idx_inventarios_empresa_id
    on public.inventarios(empresa_id);

create index if not exists idx_inventarios_unidade_id
    on public.inventarios(unidade_id);

create index if not exists idx_inventarios_usuario_id
    on public.inventarios(usuario_id);

-- =====================================================================
-- 14. MOVIMENTAÇÕES DE ESTOQUE
-- =====================================================================

create table if not exists public.estoque_movimentacoes (
    id bigint generated by default as identity primary key,
    empresa_id uuid not null
        references public.empresas(id) on delete restrict,
    produto_id bigint not null
        references public.produtos(id) on delete restrict,
    unidade_id uuid not null
        references public.unidades(id) on delete restrict,
    tipo text not null
        check (tipo in ('entrada', 'saida')),
    quantidade numeric(12,3) not null
        check (quantidade > 0),
    saldo_anterior numeric(12,3),
    saldo_novo numeric(12,3),
    motivo text,
    usuario_id bigint
        references public.usuarios(id) on delete set null,
    inventario_id bigint
        references public.inventarios(id) on delete set null,
    operacao_id uuid,
    created_at timestamptz not null default now()
);

create index if not exists idx_estoque_mov_produto
    on public.estoque_movimentacoes(produto_id);

create index if not exists idx_estoque_mov_unidade
    on public.estoque_movimentacoes(unidade_id);

create index if not exists idx_estoque_mov_empresa
    on public.estoque_movimentacoes(empresa_id);

create index if not exists idx_estoque_mov_inventario
    on public.estoque_movimentacoes(inventario_id);

create index if not exists idx_estoque_mov_usuario
    on public.estoque_movimentacoes(usuario_id);

create unique index if not exists ux_estoque_mov_operacao_produto_tipo
    on public.estoque_movimentacoes(operacao_id, produto_id, tipo)
    where operacao_id is not null;

-- =====================================================================
-- 15. INTEGRIDADE EMPRESA x UNIDADE x PRODUTO
-- =====================================================================

create or replace function public.validar_contexto_estoque_v3()
returns trigger
language plpgsql
as $
declare
    v_empresa_produto uuid;
    v_empresa_unidade uuid;
begin
    select p.empresa_id
      into v_empresa_produto
      from public.produtos p
     where p.id = new.produto_id;

    select u.empresa_id
      into v_empresa_unidade
      from public.unidades u
     where u.id = new.unidade_id;

    if v_empresa_produto is null or v_empresa_unidade is null then
        raise exception 'Produto ou unidade inexistente.';
    end if;

    if v_empresa_produto <> v_empresa_unidade then
        raise exception 'Produto e unidade possuem contextos empresariais incompatíveis.';
    end if;

    -- estoque_produto_unidade não possui empresa_id: a empresa é derivada
    -- do produto e da unidade.
    if TG_TABLE_NAME = 'estoque_movimentacoes' then
        if new.empresa_id <> v_empresa_produto then
            raise exception 'Empresa, produto e unidade possuem contextos incompatíveis.';
        end if;
    end if;

    return new;
end;
$;

drop trigger if exists trg_validar_estoque_produto_unidade_v3
    on public.estoque_produto_unidade;

create trigger trg_validar_estoque_produto_unidade_v3
before insert or update on public.estoque_produto_unidade
for each row execute function public.validar_contexto_estoque_v3();

drop trigger if exists trg_validar_estoque_movimentacao_v3
    on public.estoque_movimentacoes;

create trigger trg_validar_estoque_movimentacao_v3
before insert or update on public.estoque_movimentacoes
for each row execute function public.validar_contexto_estoque_v3();

-- =====================================================================
-- 16. INTEGRIDADE EMPRESA x UNIDADE DO INVENTÁRIO
-- =====================================================================

create or replace function public.validar_inventario_empresa_unidade_v3()
returns trigger
language plpgsql
as $$
begin
    if not exists (
        select 1
        from public.unidades u
        where u.id = new.unidade_id
          and u.empresa_id = new.empresa_id
    ) then
        raise exception 'A unidade do inventário não pertence à empresa.';
    end if;

    return new;
end;
$$;

drop trigger if exists trg_validar_inventario_empresa_unidade_v3
    on public.inventarios;

create trigger trg_validar_inventario_empresa_unidade_v3
before insert or update on public.inventarios
for each row execute function public.validar_inventario_empresa_unidade_v3();

-- =====================================================================
-- 17. VIEWS BÁSICAS DE CONSULTA
-- =====================================================================

create or replace view public.v_estoque_produto_unidade_v3 as
select
    e.id,
    e.produto_id,
    p.empresa_id,
    e.unidade_id,
    p.nome as produto_nome,
    p.categoria,
    p.controlar_estoque,
    p.estoque_minimo,
    e.saldo,
    e.updated_at
from public.estoque_produto_unidade e
join public.produtos p on p.id = e.produto_id;

create or replace view public.v_membros_organizacao_v3 as
select
    mo.id,
    mo.usuario_id,
    u.usuario,
    u.nome as usuario_nome,
    mo.empresa_id,
    e.nome as empresa_nome,
    mo.unidade_id,
    un.nome as unidade_nome,
    mo.papel_id,
    p.codigo as papel_codigo,
    p.nome as papel_nome,
    mo.ativo
from public.membros_organizacao mo
join public.usuarios u on u.id = mo.usuario_id
join public.empresas e on e.id = mo.empresa_id
left join public.unidades un on un.id = mo.unidade_id
join public.papeis p on p.id = mo.papel_id;

commit;
